version: '3'

networks:
  webapp:

services:

  nginx:
    image: nginx:stable
    container_name: ${APP_NAME}_nginx
    ports:
      - "8000:80"
    links:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app
      - mysql
    networks:
      - webapp

  app:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_app
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    environment:
      - "DB_HOST=${DB_CONNECTION}"
      - 'DB_USERNAME=${DB_USERNAME}'
      - 'DB_DATABASE=${DB_DATABASE}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
    networks:
      - webapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin    
    links:
      - mysql:db
    depends_on:
      - mysql
    ports:
      - 9393:80
    environment:
      - "UPLOAD_LIMIT=1G"
      - "PMA_PORT=33065"
    networks:
      - webapp

  mysql:
    image: mysql:8.0.26
    container_name: ${APP_NAME}_mysql
    restart: always
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - "33065:3306"
    networks:
      - webapp